name: Prepare Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  call-prepare:
    uses: leoweyr/github-release-workflow/.github/workflows/reusable-prepare-release.yml@develop
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
