name: Publish Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  call-publish:
    uses: leoweyr/github-release-workflow/.github/workflows/reusable-publish-release.yml@develop
    with:
      trb-repository: 'ODCLAB/odyssey-plan'
      trb-project-node-name: 'Tokenforge'
    secrets:
      ACCESS_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
